### PR TITLE
Simple component stories

### PR DESCRIPTION
**Pull request by mariasereno-png**
## What it does, and why

StatusDot, StyledLink, Tag, TextArea, TextInput ported to Storybook.

Need checks on whether forwardRef still works as intended (had to tweak how the TextArea and TextInput components rendered to get them Storybook-ready, but the change may have affected the ref) - @shomukai @abottega if you could please check that would be awesome!

### CODE REVIEW

**Comment by deividasm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           

Complexity increasing per file
==============================
- lib/components/Tag/Tag.stories.js  1
- lib/components/StatusDot/StatusDot.stories.js  1
- lib/components/TextArea/TextArea.stories.js  1
- lib/components/StyledLink/StyledLink.stories.js  1
         

Clones added
============
- lib/components/Tag/index.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Orchestrated/orca-design-system/pullRequest?prid=4626369&bid=15509328)

**Comment by deividasm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           

Complexity increasing per file
==============================
- lib/components/Tag/Tag.stories.js  1
- lib/components/StatusDot/StatusDot.stories.js  1
- lib/components/StyledLink/StyledLink.stories.js  1
- lib/components/TextArea/TextArea.stories.js  1
         

Clones added
============
- lib/components/Tag/index.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Orchestrated/orca-design-system/pullRequest?prid=4626369&bid=15509328)

**Comment by mariasereno-png** [comment]
Yup, can do!

I actually had changed functional components to class-based ones (oops)
because I thought that was how we wanted to do things. I can go back and
fix the previous components I've done as well.

**Comment by deividasm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           

Complexity increasing per file
==============================
- lib/components/Tag/Tag.stories.js  1
- lib/components/StatusDot/StatusDot.stories.js  1
- lib/components/TextArea/TextArea.stories.js  1
- lib/components/StyledLink/StyledLink.stories.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Orchestrated/orca-design-system/pullRequest?prid=4626369&bid=15509328)

**Comment by deividasm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- lib/components/StatusDot/StatusDot.stories.js  1
- lib/components/StyledLink/StyledLink.stories.js  1
- lib/components/Tag/Tag.stories.js  1
- lib/components/TextArea/TextArea.stories.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Orchestrated/orca-design-system/pullRequest?prid=4626369&bid=15509328)

**Comment by deividasm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- lib/components/StyledLink/StyledLink.stories.js  1
- lib/components/Toggle/Toggle.stories.js  1
- lib/components/Tag/Tag.stories.js  1
- lib/components/StatusDot/StatusDot.stories.js  1
- lib/components/TextArea/TextArea.stories.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Orchestrated/orca-design-system/pullRequest?prid=4626369&bid=15509328)

**Comment by deividasm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- lib/components/StyledLink/StyledLink.stories.js  1
- lib/components/StatusDot/StatusDot.stories.js  1
- lib/components/TextArea/TextArea.stories.js  1
- lib/components/Toggle/Toggle.stories.js  1
- lib/components/Tag/Tag.stories.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Orchestrated/orca-design-system/pullRequest?prid=4626369&bid=15509328)

**Comment by deividasm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- lib/components/StyledLink/StyledLink.stories.js  1
- lib/components/TextArea/TextArea.stories.js  1
- lib/components/StatusDot/StatusDot.stories.js  1
- lib/components/Tag/Tag.stories.js  1
- lib/components/Toggle/Toggle.stories.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Orchestrated/orca-design-system/pullRequest?prid=4626369&bid=15509328)

**Comment by deividasm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- lib/components/Toggle/Toggle.stories.js  1
- lib/components/Tag/Tag.stories.js  1
- lib/components/TextArea/TextArea.stories.js  1
- lib/components/StyledLink/StyledLink.stories.js  1
- lib/components/StatusDot/StatusDot.stories.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Orchestrated/orca-design-system/pullRequest?prid=4626369&bid=15509328)

**Pull request merged**
